# 03_HW664_LIS3DH - core1 (appcpu) image
#
# This core never touches the accelerometer, only the SSD1306 over I2C1 and
# the IPM mailbox from core0.

CONFIG_I2C=y
CONFIG_GPIO=y

CONFIG_IPM=y
CONFIG_ESP32_SOFT_IPM=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_FPU=y
