# 02_GY521_MPU6050 - core1 (appcpu) image
#
# No CONFIG_SENSOR here - this core never touches the MPU6050, only
# the SSD1306 over I2C1 and the IPM mailbox from core0.

CONFIG_I2C=y
CONFIG_GPIO=y

CONFIG_IPM=y
CONFIG_ESP32_SOFT_IPM=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_FPU=y
